print("First Line")
print("AAA")
print("BBB")
print("CCC")
print("DDD")
print("Second Line")
print("AAA")
print("BBB")
print("CCC")
print("DDD")
print("Third Line")
print("AAA")
print("BBB")
print("CCC")
print("DDD")
print("Fourth Line")
print("AAA")
print("BBB")
print("CCC")
print("DDD")
print("Fifth Line")